//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    using Microcolsa.Suite.Core.ConsultaInternet;
    
    public partial class ArchivadoresUsuario
    {
        public int Id { get; set; }
        public int IdArchivador { get; set; }
        public int IdUsuario { get; set; }
        public byte Habilitado { get; set; }
    
        public virtual Archivador Archivadores { get; set; }
        public virtual Usuario Usuarios { get; set; }
    }
}
