//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    using Microcolsa.Suite.Core.ConsultaInternet;
    
    public partial class mci_ArchvdorVncldo
    {
        public mci_ArchvdorVncldo()
        {
            this.mci_CmpoArchvdorVncldo = new HashSet<mci_CmpoArchvdorVncldo>();
        }
    
        public int intId { get; set; }
        public int intIdCnfgrcion { get; set; }
        public int intIdArchvdorPdre { get; set; }
    
        public virtual Archivador mci_Archvdor { get; set; }
        public virtual ICollection<mci_CmpoArchvdorVncldo> mci_CmpoArchvdorVncldo { get; set; }
    }
}
