//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mci_SbCnfigMcrclsaDcments
    {
        public mci_SbCnfigMcrclsaDcments()
        {
            this.mci_TpoArchvdor = new HashSet<TipoArchivador>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TipoArchivador> mci_TpoArchvdor { get; set; }
    }
}
