//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    using Microcolsa.Suite.Core.ConsultaInternet;
    
    public partial class mci_PrmsoCmpo
    {
        public int intId { get; set; }
        public Nullable<int> intIdUsrio { get; set; }
        public Nullable<int> intIdGrpo { get; set; }
        public int intIdArchvdor { get; set; }
        public string strCmpo { get; set; }
        public string strCndcnal { get; set; }
        public string strValor { get; set; }
    
        public virtual Archivador mci_Archvdor { get; set; }
        public virtual mcu_Grpo mcu_Grpo { get; set; }
        public virtual Usuario mcu_Usrio { get; set; }
    }
}
