//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcu_Grpo
    {
        public mcu_Grpo()
        {
            this.mci_ArchvdresGrpo = new HashSet<mci_ArchvdresGrpo>();
            this.mci_PrmsoCmpo = new HashSet<mci_PrmsoCmpo>();
            this.mcu_GrpoUsrio = new HashSet<mcu_GrpoUsrio>();
        }
    
        public int intId { get; set; }
        public string strNmbre { get; set; }
        public string strDscrpcion { get; set; }
    
        public virtual ICollection<mci_ArchvdresGrpo> mci_ArchvdresGrpo { get; set; }
        public virtual ICollection<mci_PrmsoCmpo> mci_PrmsoCmpo { get; set; }
        public virtual ICollection<mcu_GrpoUsrio> mcu_GrpoUsrio { get; set; }
    }
}
