//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcu_AplccionUsrio
    {
        public mcu_AplccionUsrio()
        {
            this.mcu_MdloAplccion = new HashSet<mcu_MdloAplccion>();
        }
    
        public int intId { get; set; }
        public byte[] Aplicacion { get; set; }
    
        public virtual ICollection<mcu_MdloAplccion> mcu_MdloAplccion { get; set; }
    }
}
