//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    using Microcolsa.Suite.Core.ConsultaInternet;
    
    public partial class TipoArchivador
    {
        public TipoArchivador()
        {
            this.Archivadores = new HashSet<Archivador>();
        }
    
        public int Id { get; set; }
        public int IdSubconfiguracion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Archivador> Archivadores { get; set; }
        public virtual mci_SbCnfigDcwre mci_SbCnfigDcwre { get; set; }
        public virtual mci_SbCnfigMcrclsaDcments mci_SbCnfigMcrclsaDcments { get; set; }
        public virtual mci_SbCnfigShrePoint mci_SbCnfigShrePoint { get; set; }
    }
}
