//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ArchivadoresUsuario = new HashSet<ArchivadoresUsuario>();
            this.mci_PrmsoCmpo = new HashSet<mci_PrmsoCmpo>();
            this.mcu_GrpoUsrio = new HashSet<mcu_GrpoUsrio>();
            this.mcu_ScrslesUsrio = new HashSet<mcu_ScrslesUsrio>();
            this.mcu_Usrio1 = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdTipoIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdSubdependencia { get; set; }
        public Nullable<int> IdCentroDeCostos { get; set; }
        public Nullable<int> IdUsuarioJefe { get; set; }
    
        public virtual ICollection<ArchivadoresUsuario> ArchivadoresUsuario { get; set; }
        public virtual ICollection<mci_PrmsoCmpo> mci_PrmsoCmpo { get; set; }
        public virtual mcu_CCsto mcu_CCsto { get; set; }
        public virtual ICollection<mcu_GrpoUsrio> mcu_GrpoUsrio { get; set; }
        public virtual mcu_SbDpndncia mcu_SbDpndncia { get; set; }
        public virtual ICollection<mcu_ScrslesUsrio> mcu_ScrslesUsrio { get; set; }
        public virtual mcu_SgntreUsrio mcu_SgntreUsrio { get; set; }
        public virtual mcu_TpoIdntfccion mcu_TpoIdntfccion { get; set; }
        public virtual ICollection<Usuario> mcu_Usrio1 { get; set; }
        public virtual Usuario mcu_Usrio2 { get; set; }
    }
}
